### ISSUE TITLE
NullPointer while trying to extract method

### ISSUE THREAD

**Issue by tivervac** [eclipse/xtext-extras#107] opened 2017-01-26 09:51 UTC
Using Xtext Complete SDK 2.10.0v201605250459 in Eclipse 4.6.2
```
java.lang.NullPointerException
	at org.eclipse.xtext.xbase.compiler.AbstractStringBuilderBasedAppendable.append(AbstractStringBuilderBasedAppendable.java:60)
	at org.eclipse.xtext.xbase.compiler.AbstractStringBuilderBasedAppendable.append(AbstractStringBuilderBasedAppendable.java:1)
	at org.eclipse.xtend.ide.refactoring.ExtractMethodRefactoring.appendMethodSignature(ExtractMethodRefactoring.java:307)
	at org.eclipse.xtend.ide.refactoring.ExtractMethodRefactoring.getMethodSignature(ExtractMethodRefactoring.java:279)
	at org.eclipse.xtend.ide.refactoring.ExtractMethodUserInputPage.createSignaturePreview(ExtractMethodUserInputPage.java:208)
	at org.eclipse.xtend.ide.refactoring.ExtractMethodUserInputPage.createControl(ExtractMethodUserInputPage.java:91)
	at org.eclipse.ltk.internal.ui.refactoring.RefactoringWizardDialog2.createContents(RefactoringWizardDialog2.java:625)
	at org.eclipse.jface.window.Window.create(Window.java:426)
	at org.eclipse.jface.dialogs.Dialog.create(Dialog.java:1095)
	at org.eclipse.xtext.ui.refactoring.ui.RefactoringWizardOpenOperation_NonForking$1.run(RefactoringWizardOpenOperation_NonForking.java:103)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.xtext.ui.refactoring.ui.RefactoringWizardOpenOperation_NonForking.run(RefactoringWizardOpenOperation_NonForking.java:126)
	at org.eclipse.xtext.ui.refactoring.ui.RefactoringWizardOpenOperation_NonForking.run(RefactoringWizardOpenOperation_NonForking.java:71)
	at org.eclipse.xtend.ide.refactoring.ExtractMethodHandler.execute(ExtractMethodHandler.java:81)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:295)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:90)
	at sun.reflect.GeneratedMethodAccessor290.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:282)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:264)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:494)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:488)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.executeCommand(KeyBindingDispatcher.java:286)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.press(KeyBindingDispatcher.java:507)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.processKeyEvent(KeyBindingDispatcher.java:558)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.filterKeySequenceBindings(KeyBindingDispatcher.java:378)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.access$0(KeyBindingDispatcher.java:324)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher$KeyDownFilter.handleEvent(KeyBindingDispatcher.java:86)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.filterEvent(Display.java:1605)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1339)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1366)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1349)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1378)
	at org.eclipse.swt.widgets.Widget.gtk_key_press_event(Widget.java:764)
	at org.eclipse.swt.widgets.Control.gtk_key_press_event(Control.java:3465)
	at org.eclipse.swt.widgets.Composite.gtk_key_press_event(Composite.java:801)
	at org.eclipse.swt.widgets.Widget.windowProc(Widget.java:2000)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:5827)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5498)
	at org.eclipse.swt.internal.gtk.OS._gtk_main_do_event(Native Method)
	at org.eclipse.swt.internal.gtk.OS.gtk_main_do_event(OS.java:9545)
	at org.eclipse.swt.widgets.Display.eventProc(Display.java:1275)
	at org.eclipse.swt.internal.gtk.OS._g_main_context_iteration(Native Method)
	at org.eclipse.swt.internal.gtk.OS.g_main_context_iteration(OS.java:2495)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4149)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:693)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:610)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1488)
```

**Comment by cdietrich** [comment] 2017-01-26 09:53
hi, can you share the producing code snippet as well?

**Comment by kthoms** [comment] 2017-01-26 09:57
This seems to happen when the "Extract Method" refactoring is performed. The refactoring wants to declare an explicit return type, but the return type reference is null. We have to know under which circumstances this could happen.
Could you share more information about the refactoring context, e.g. the code snippet that you would like to extract to a method? Could this be reproduced with a simple example?

**Comment by tivervac** [comment] 2017-01-26 12:49
The following code produces the same error when trying to extract a method from the body of `test`.
```
import java.util.ArrayList

class Test {
	def void test() {
		val int a = 5
		new ArrayList<Integer>.addAll(#[a])
	}
}
```

**Comment by kthoms** [comment] 2017-01-26 13:24
Thanks, this is reproducible.

**Comment by cdietrich** [comment] 2017-01-27 08:33
`typeComputationServices.getTypeConformanceComputer().getCommonSuperType(returnTypes, owner)` of `[void, boolean, boolean]` is null.

the follow up code does not exepect that

**Comment by kthoms** [comment] 2017-02-03 07:42
The proposed change would fix the NPE, but the actual problem is that the return type is not computed correctly. Consider this file:

package test

import java.util.ArrayList
import org.eclipse.xtend.lib.annotations.Data

class Foo {
	Bar thisEnd
	def boolean test() {
		val int a = 5
		val x = '''«thisEnd.name»'''
		return new ArrayList<Integer>.addAll(#[a])
	}
}

@Data
class Bar {
	String name
}

If you extract the two lines val x = ... and return ..., then the refactoring would now determine void as the type. This will lead to a compile error, since the extracted method has a return statement with a type expectation, but it is incompatible with the declared return type void.

**Comment by kthoms** [comment] 2017-02-03 07:45
For a workaround, how about suppressing the return type declaration and disable the "Explicit declare return type" option in the dialog? Again, this would not fix the actual problem, but should be realizable in reasonable effort and would lead to compilable code.

**Comment by svenefftinge** [comment] 2017-03-29 10:28
see https://github.com/eclipse/xtext-extras/pull/128
and https://github.com/eclipse/xtext-xtend/pull/190

**Comment by svenefftinge** [comment] 2017-03-29 11:29
merged the PRs. Thanks everyone for investigation.

**Closed by svenefftinge** 2017-03-29 11:29 UTC
Labels: bug, confirmed
